const items = [
  {
    id: 0,
    name: "air freshener",
    imgUrl: "/imgs/air-freshener.jpg",
    price: 5.99,
    currency: "euro",
  },
  {
    id: 1,
    name: "apple",
    imgUrl: "/imgs/apple.jpeg",
    price: 1.99,
    currency: "euro",
  },
  {
    id: 2,
    name: "beef",
    imgUrl: "/imgs/beef.jpg",
    price: 7.49,
    currency: "euro",
  },
  {
    id: 3,
    name: "book",
    imgUrl: "/imgs/book.webp",
    price: 19.99,
    currency: "euro",
  },
  {
    id: 4,
    name: "bowl",
    imgUrl: "/imgs/bowl.webp",
    price: 8.19,
    currency: "euro",
  },
  {
    id: 5,
    name: "brocolli",
    imgUrl: "/imgs/brocolli.png",
    price: 5.39,
    currency: "euro",
  },
  {
    id: 6,
    name: "clock",
    imgUrl: "/imgs/clock.jpg",
    price: 21,
    currency: "euro",
  },
  {
    id: 7,
    name: "desk",
    imgUrl: "/imgs/desk.avif",
    price: 159.49,
    currency: "euro",
  },
  {
    id: 8,
    name: "ice cube tray",
    imgUrl: "/imgs/ice-cube-tray.webp",
    price: 4.2,
    currency: "euro",
  },
  {
    id: 9,
    name: "mirror",
    imgUrl: "/imgs/mirror.jpeg",
    price: 23.19,
    currency: "euro",
  },
  {
    id: 10,
    name: "pillow",
    imgUrl: "/imgs/pillow.avif",
    price: 37.99,
    currency: "euro",
  },
  {
    id: 11,
    name: "rubber band",
    imgUrl: "/imgs/rubber-band.webp",
    price: 1.99,
    currency: "euro",
  },
  {
    id: 12,
    name: "sidewalk",
    imgUrl: "/imgs/sidewalk.png",
    price: 9000.01,
    currency: "euro",
  },
  {
    id: 13,
    name: "slippers",
    imgUrl: "/imgs/slippers.avif",
    price: 22.47,
    currency: "euro",
  },
  {
    id: 14,
    name: "twister",
    imgUrl: "/imgs/twister.jpg",
    price: 7.49,
    currency: "euro",
  },
];

export default items;
